name: sample-go-pprof
run-name: ${{ github.actor }} building...
on: 
  push:
    branches:
      - main
env:
  GO_VERSION: "1.19.1"

jobs:
  verify-code:
    name: Verify code
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Verify Go code
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          args: --verbose
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Vendor Go modules
        run: go mod vendor